import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser = await chromium.launch({headless:true});
const page = await browser.newPage({viewport:{width:1280,height:800}});
const errors=[];page.on('pageerror', e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173/preview/');
await page.getByRole('button',{name:/Battle notes/}).waitFor();
await page.getByText(/possible moves · none seen/).click();
await page.getByText('+2 Atk', {exact:false}).first().waitFor();
await page.screenshot({path:'artifacts/whiteboard-desktop.png'});
await page.getByRole('button',{name:'Flamethrower',exact:true}).hover();
await page.getByRole('tooltip').waitFor();
await page.screenshot({path:'artifacts/whiteboard-tooltip.png'});
await page.getByRole('button',{name:/Battle notes/}).click();
assert.equal(await page.locator('#ps-board-body').count(),0);
await page.getByRole('button',{name:/Battle notes/}).focus();
await page.keyboard.press('Enter');
assert.equal(await page.locator('#ps-board-body').count(),1);
await page.setViewportSize({width:390,height:844});
await page.mouse.move(0,0);
await page.screenshot({path:'artifacts/whiteboard-mobile.png'});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
const bounds=await page.locator('.ps-board').boundingBox();
assert.ok(bounds.x>=0 && bounds.x+bounds.width<=390);
await page.reload();
await page.getByRole('button',{name:/Battle notes/}).waitFor();
assert.equal(await page.getByRole('button',{name:/Battle notes/}).getAttribute('aria-expanded'),'false');
assert.equal(await page.locator('#ps-board-body').count(),0);
assert.deepEqual(errors,[]);
await browser.close();
console.log('Desktop, narrow layout, tooltip, keyboard collapse, and console checks passed.');
